# Generated by Django 3.2.9 on 2021-12-01 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, help_text="Automatically generated by concatenating the parent's path and the slug unless the path is defined manually.", max_length=1000, unique=True, validators=[django.core.validators.RegexValidator(message='Path must start and end with a slash (/).', regex='^/(|.+/)$')], verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_to_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Redirect to URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='static_path',
            field=models.BooleanField(default=False, verbose_name='manually define the path'),
        ),
        migrations.AlterField(
            model_name='richtext',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
